---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/alexakru/public_html/
    - /bin/cp -r /home3/alexakru/portfolio-site/build/* $DEPLOYPATH
    - /bin/cp -r /home3/alexakru/portfolio-site/.htaccess $DEPLOYPATH